export const GET_MECHANICAL_DASHBOARD_REQUEST =
  "GET_MECHANICAL_DASHBOARD_REQUEST";

export const GET_MECHANICAL_DASHBOARD_SUCCESS =
  "GET_MECHANICAL_DASHBOARD_SUCCESS";

export const GET_MECHANICAL_DASHBOARD_FAILURE =
  "GET_MECHANICAL_DASHBOARD_FAILURE";