export const GET_TEST_ANALYTICS_REQUEST =
  "GET_TEST_ANALYTICS_REQUEST";

export const GET_TEST_ANALYTICS_SUCCESS =
  "GET_TEST_ANALYTICS_SUCCESS";

export const GET_TEST_ANALYTICS_FAILURE =
  "GET_TEST_ANALYTICS_FAILURE";